import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthContext } from "./Contaxtapi/AuthContext";
import { NavBar } from "./_Component/NavBar";
import { LargeFooter } from "./_Component/Fotter";
import { DataProvider } from "./Contaxtapi/DataProvide";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthContext>
         
          <NavBar></NavBar> <DataProvider> {children} </DataProvider> <LargeFooter></LargeFooter>
        </AuthContext>
      </body>
    </html>
  );
}
